spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: mysql_db

  sql:
    init:
      encoding: utf-8
      mode: always

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/