spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: mysql_db

  sql:
    init:
      encoding: utf-8
      mode: always

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  schedule: # interval 1 hour
    cron : 0 0 0/1 * * *
    use : true
    
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: chanhyeog@gmail.com
    password: ${GOOGLE_APP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls.enable: true
          auth: true


youtube:
    api:
      key: ${YOUTUBE_API_KEY}

alan:
    one:
      url: ${ALAN_ONE_URL}
client:
  id: ${CLIENT_ID}

cloud:
  aws:
    s3:
      bucket: simsasookbak
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

